#!/bin/sh

set -eu

# 3, 客户端配置

# 初始化环境变量
source $OPENVPN/ovpn_env

# 定义环境变量
OVPN_REMOTE=$REMOTE_IP
OVPN_CLIENT_KEY=$OVPN_PKI/private/$OVPN_REMOTE-client.key
OVPN_CLIENT_REQ=$OVPN_PKI/reqs/$OVPN_REMOTE-client.req
OVPN_CLIENT_CRT=$OVPN_PKI/issued/$OVPN_REMOTE-client.crt
OVPN_CLIENT_CONFIG=$OPENVPN/$OVPN_REMOTE.ovpn

if [ -f $OVPN_CLIENT_CONFIG ]; then
  echo "$OVPN_CLIENT_CONFIG配置文件已存在, 跳过初始化"
  exit
fi

if [[ ! -f $OVPN_CLIENT_KEY || -f $OVPN_CLIENT_REQ ]]; then
  # 缺少私钥或证书
  rm -fr $OVPN_CLIENT_KEY $OVPN_CLIENT_REQ $OVPN_CLIENT_CRT
fi

# 生成客户端端证书
cd ${OVPN_PKI%/*}
easyrsa build-client-full $OVPN_REMOTE-client nopass

# 生成openvpn客户端配置文件
cat > "$OVPN_CLIENT_CONFIG" << END
client
nobind
dev tun

remote $OVPN_REMOTE $OVPN_PORT $OVPN_PROTO
resolv-retry infinite
remote-cert-tls server

<key>
$(cat $OVPN_CLIENT_KEY)
</key>
<cert>
$(openssl x509 -in $OVPN_CLIENT_CRT)
</cert>
<ca>
$(cat $OVPN_CA_CRT)
</ca>
key-direction 1
<tls-auth>
$(cat $OVPN_TA_KEY)
</tls-auth>
END
echo "$OVPN_CLIENT_CONFIG 客户端配置文件已生成"
