#!/bin/sh

set -eu

# 1, 初始化PKI

# 定义环境变量
EASYRSA_PKI=/etc/openvpn/pki
EASYRSA=/usr/share/easy-rsa
alias easyrsa="$EASYRSA/easyrsa"

# 初始化操作
rm -fr $EASYRSA_PKI
cd ${EASYRSA_PKI%/*}
# 初始化pki目录
easyrsa init-pki
# 生成CA证书
echo | easyrsa build-ca nopass
# 生成服务端证书
easyrsa build-server-full $HOST_IP-server nopass
easyrsa gen-dh
# 生成客户端端证书
easyrsa build-client-full $HOST_IP-client nopass
