#!/bin/sh

set -eu

# 1, 初始化PKI

# 初始化环境变量
source ${OPENVPN}/ovpn_env

# 初始化操作
rm -fr $OVPN_PKI
cd ${OVPN_PKI%/*}
# 初始化pki目录
easyrsa init-pki
# 生成CA证书
echo ${OVPN_CN} | easyrsa build-ca nopass
# 生成服务端证书
easyrsa build-server-full ${OVPN_CN}-server nopass
#easyrsa gen-dh
openssl dhparam -out $OVPN_SERVER_DH 1024
