#!/bin/sh

set -eu

# 2, 服务端配置

# 初始化环境变量
source ${OPENVPN}/ovpn_env

# 生成tls认证秘钥
if [ ! -f $OVPN_TA_KEY ]; then
  openvpn --genkey --secret $OVPN_TA_KEY
fi

# 生成openvpn服务端配置文件
cat > "$OVPN_SERVER_CONFIG" << END
proto $OVPN_PROTO
port $OVPN_PORT
dev $OVPN_DEVICE$OVPN_DEVICEN

ca $OVPN_CA_CRT
key $OVPN_SERVER_KEY
cert $OVPN_SERVER_CRT
dh $OVPN_SERVER_DH

server ${OVPN_SERVER%/*} $(ipcalc -m $OVPN_SERVER | awk -F '=' '{print $2}')

keepalive $OVPN_KEEPALIVE
duplicate-cn

key-direction 0
tls-auth $OVPN_TA_KEY

status /tmp/openvpn-status.log
verb 3

persist-key
persist-tun

user nobody
group nogroup
END
